#!/bin/bash
[ -d data/run ] && rm -r data/run
docker build -t sysinit -f sysinit/Dockerfile . >/dev/null 2>/dev/null
docker run -it --rm --name sysinit \
    -v ./data:/data \
    -v ./data/etc/letsencrypt:/etc/letsencrypt \
    -v ./data/var/lib/letsencrypt:/var/lib/letsencrypt \
    -v ./.env:/.env \
    -v ./sysinit/initdb.sql:/initdb.sql \
    -v ./sysinit/imapsync-mboxes.csv:/imapsync-mboxes.csv \
    -p 80:80 sysinit
