#!/bin/bash
. .env

docker compose down
rm -r data/tmp
if [ "$1" == "-r" ] ; then
  docker compose build --no-cache
fi

[ -d data/run ] && rm -r data/run

PARMS=""
[ "$RUN_IMAPSYNC" -eq 1 ] && PARMS="$PARMS --profile imapsync"
[ "$RUN_WEBMAIL" -eq 1 ] && PARMS="$PARMS --profile webmail"

docker compose $PARMS up
