#!/bin/bash
. .env

[ ! -d ${DATA_DIR}/var/log ] && mkdir -p ${DATA_DIR}/var/log
[ ! -d ${DATA_DIR}/var/log/imapsync ] && mkdir -p ${DATA_DIR}/var/log/imapsync
chown ${GOMAIL_USER}:${GOMAIL_GROUP} -R ${DATA_DIR}
chmod 777 -R ${DATA_DIR}

docker compose down
[ -d data/run ] && rm -r data/run
docker compose up
